In [5]:
import numpy as np

def custom_matrix_multiply(A, B):
    if A.shape[1] != B.shape[0]:
        raise ValueError("Incompatible dimensions for matrix multiplication.")
    
    result = np.zeros((A.shape[0], B.shape[1]))
    
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(B.shape[0]):
                result[i][j] += A[i][k] * B[k][j]
    
    return result
A = np.array([[1, 6], [3, 4]])
B = np.array([[5, 7], [10, 8]])

result = custom_matrix_multiply(A, B)
print("Matrix Multiplication Result:\n", result)


Matrix Multiplication Result:
 [[65. 55.]
 [55. 53.]]


In [9]:
data = np.array([50, 20, 30, 80, 100], dtype=float)
print(data)

[ 50.  20.  30.  80. 100.]


In [11]:
def min_max_scaling(x):
    x_min = np.min(x)
    x_max = np.max(x)
    return (x - x_min) / (x_max - x_min)

scaled_data = min_max_scaling(data)
print("Min-Max Scaled:\n", scaled_data)


Min-Max Scaled:
 [0.375 0.    0.125 0.75  1.   ]


In [13]:
def standardize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

standardized_data = standardize(data)
print("Standardized Data:\n", standardized_data)


Standardized Data:
 [-0.19955703 -1.19734219 -0.86474714  0.79822813  1.46341823]
